### ISSUE TITLE
images of some characters not loading

### ISSUE THREAD

**Issue by Danielsilverio81** [hellskater/narutodb-website#48]
images of some characters not loading
I'm using react and calling the api using axios, I get a successful return, but some images do not appear and the console shows a 404 error referring to the image
![2023-07-17 (1)](https://github.com/hellskater/narutodb-website/assets/92233752/b8cbf9fd-4723-4482-a6f2-e0c9f8719409)

**Comment by AESMatias** [comment]
> images of some characters not loading I'm using react and calling the api using axios, I get a successful return, but some images do not appear and the console shows a 404 error referring to the image ![2023-07-17 (1)](https://private-user-images.githubusercontent.com/92233752/254077769-b8cbf9fd-4723-4482-a6f2-e0c9f8719409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTc4OTIsIm5iZiI6MTcwNzkxNzU5MiwicGF0aCI6Ii85MjIzMzc1Mi8yNTQwNzc3NjktYjhjYmY5ZmQtNDcyMy00NDgyLWE2ZjItZTBjOWY4NzE5NDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzMzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OTQ2ODY2YTk3MjUxZWYyMTY4OTA4ZDMxZTRjY2U4OWY4NThmMWE1ZGQyNGQ5NTVkNmQ4OGRmMzRjMTNiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a4qchx6YcrzBZy3tU32XIH6iu63GFtezeTPmOzVzYQc)

Same issue here! I lean towards catch the error and handle it in the meanwhile.
I will add that some images are empty and do not prompt the 404 error properly, so i suggest being careful with that too.

**Comment by hellskater** [comment]
I understand the issue. But the images are not hosted by us, they are scraped.
